// examples/input-mask-react/src/examples/maskito/components/TextArea/TextArea.jsx
import { useMaskito } from '@maskito/react';
import { BlTextarea } from '@trendyol/baklava/dist/baklava-react';

import options from './mask';
import { elementPredicate } from '../../helpers';

export default function TextArea() {
  const maskedInputRef = useMaskito({
    options,
    elementPredicate,
  });

  return (
    <BlTextarea
      ref={maskedInputRef}
      size="large"
      name="textarea"
      label="Address"
      placeholder="Enter your address"
      spellCheck
    />
  );
}

// examples/input-mask-vue/src/examples/maskito/components/TextArea/TextArea.vue
<template>
  <bl-textarea
    v-maskito="options"
    size="large"
    name="textarea"
    label="Address"
    placeholder="Enter your address"
    spellcheck
  />
</template>

<script>
import { defineComponent } from 'vue';
import { maskito } from '@maskito/vue';
import maskOptions from './mask';
import { elementPredicate } from '../../helpers';

export default defineComponent({
  name: 'TextArea',
  directives: {
    maskito,
  },
  setup() {
    const options = {
      ...maskOptions,
      elementPredicate,
    };

    return {
      options,
    };
  },
});
</script>
