// examples/input-mask-react/src/examples/imask/components/InputPhoneKazakhstan/InputPhoneKazakhstan.jsx
import { BlInput } from '@trendyol/baklava/dist/baklava-react';
import { useIMaskWithObserver } from '../../hooks';

export default function InputPhoneKazakhstan() {
  const ref = useIMaskWithObserver({
    mask: '+7 (000) 000-00-00',
  });

  return (
    <BlInput
      ref={ref}
      size="large"
      icon="phone"
      label="Phone Number"
      placeholder="Enter phone number"
      name="phone-kazakhstan"
      labelFixed
    />
  );
}

// examples/input-mask-vue/src/examples/imask/components/InputPhoneKazakhstan/InputPhoneKazakhstan.vue
<template>
  <bl-input
    ref="blInputRef"
    size="large"
    icon="phone"
    label="Phone Number"
    placeholder="Enter phone number"
    name="phone-kazakhstan"
    label-fixed
  />
</template>

<script>
import { defineComponent } from 'vue';
import { useIMaskWithObserver } from '../../hooks/useIMaskWithObserver';

export default defineComponent({
  name: 'InputPhoneKazakhstan',
  setup() {
    const { el: blInputRef } = useIMaskWithObserver({
      mask: '+7 (000) 000-00-00',
    });

    return {
      blInputRef,
    };
  },
});
</script>
