// examples/input-mask-react/src/examples/imask/components/TextArea/TextArea.jsx
import { BlTextarea } from '@trendyol/baklava/dist/baklava-react';
import { useIMaskWithObserver } from '../../hooks';

export default function TextArea() {
  const ref = useIMaskWithObserver({
    mask: /^[a-z1-9\s.,/]+$/i,
  });

  return (
    <BlTextarea
      ref={ref}
      size="large"
      name="textarea"
      label="Address"
      placeholder="Enter your address"
      spellCheck
    />
  );
}

// examples/input-mask-vue/src/examples/imask/components/TextArea/TextArea.vue
<template>
  <bl-textarea
    ref="blInputRef"
    size="large"
    name="textarea"
    label="Address"
    placeholder="Enter your address"
    spellcheck
  />
</template>

<script>
import { defineComponent } from 'vue';
import { useIMaskWithObserver } from '../../hooks/useIMaskWithObserver';

export default defineComponent({
  name: 'TextArea',
  setup() {
    const { el: blInputRef } = useIMaskWithObserver({
      mask: /^[a-z1-9\s.,/]+$/i,
    });

    return {
      blInputRef,
    };
  },
});
</script>
