// examples/input-mask-vue/src/examples/maskito/components/InputWithPlaceholderDate/InputWithPlaceholderDate.vue
<template>
  <bl-input
    v-maskito="options"
    size="large"
    name="date"
    label="Date"
    label-fixed
  />
</template>

<script>
import {defineComponent} from 'vue';
import {maskito} from '@maskito/vue';
import maskOptions from './mask';
import {elementPredicate} from '../../helpers';

export default defineComponent({
  name: 'InputWithPlaceholderDate',
  directives: {
    maskito,
  },
  setup() {
    const options = {
      ...maskOptions,
      elementPredicate,
    };

    return {
      options,
    };
  },
});
</script>

// examples/input-mask-react/src/examples/maskito/components/InputWithPlaceholderDate/InputWithPlaceholderDate.jsx
import { useMaskito } from '@maskito/react';
import { BlInput } from '@trendyol/baklava/dist/baklava-react';

import options from './mask';
import { elementPredicate } from '../../helpers';

export default function InputWithPlaceholderDate() {
  const maskedInputRef = useMaskito({
    options,
    elementPredicate,
  });

  return (
    <BlInput
      ref={maskedInputRef}
      size="large"
      name="date"
      label="Date"
      labelFixed
    />
  );
}
