// examples/input-mask-vue/src/examples/imask/components/InputPricePrefix/InputPricePrefix.vue
<template>
  <bl-input
    ref="blInputRef"
    size="large"
    name="price"
    label="Price"
    placeholder="Enter price"
    icon="money"
  />
</template>

<script>
import { defineComponent } from 'vue';
import { useIMaskWithObserver } from '../../hooks/useIMaskWithObserver';

export default defineComponent({
  name: 'InputPricePrefix',
  setup() {
    const { el: blInputRef } = useIMaskWithObserver({
      mask: '$num',
      blocks: {
        num: {
          mask: Number,
        },
      },
    });

    return {
      blInputRef,
    };
  },
});
</script>

// examples/input-mask-react/src/examples/imask/components/InputPricePrefix/InputPricePrefix.jsx
import { BlInput } from '@trendyol/baklava/dist/baklava-react';
import { useIMaskWithObserver } from '../../hooks';

export default function InputPricePrefix() {
  const ref = useIMaskWithObserver({
    mask: '$num',
    blocks: {
      num: {
        mask: Number,
      },
    },
  });

  return (
    <BlInput
      ref={ref}
      size="large"
      name="price"
      label="Price"
      placeholder="Enter price"
      icon="money"
    />
  );
}
