// examples/input-mask-vue/src/examples/imask/components/InputWithPlaceholderCVC/InputWithPlaceholderCVC.vue
<template>
  <bl-input
    ref="blInputRef"
    size="large"
    icon="wallet"
    label="CVC"
    placeholder="xxx"
  />
</template>

<script>
import { defineComponent } from 'vue';
import { IMask } from 'vue-imask';
import { useIMaskWithObserver } from '../../hooks/useIMaskWithObserver';

export default defineComponent({
  name: 'InputWithPlaceholderCVC',
  setup() {
    const { el: blInputRef } = useIMaskWithObserver({
      mask: IMask.MaskedRange,
      from: 0,
      to: 999,
      maxLength: 3,
      placeholderChar: 'x',
      lazy: false,
    });

    return {
      blInputRef,
    };
  },
});
</script>

// examples/input-mask-react/src/examples/imask/components/InputWithPlaceholderCVC/InputWithPlaceholderCVC.jsx
import { IMask } from 'react-imask';
import { BlInput } from '@trendyol/baklava/dist/baklava-react';
import { useIMaskWithObserver } from '../../hooks';

export default function InputWithPlaceholderCVC() {
  const ref = useIMaskWithObserver({
    mask: IMask.MaskedRange,
    from: 0,
    to: 999,
    maxLength: 3,
    placeholderChar: 'x',
    lazy: false,
  });

  return (
    <BlInput
      ref={ref}
      size="large"
      icon="wallet"
      label="CVC"
      placeholder="xxx"
    />
  );
}
