// examples/input-mask-react/src/examples/maskito/components/InputWithPrefixByPatternMaskExpression/InputWithPrefixByPatternMaskExpression.jsx
import { useMaskito } from '@maskito/react';
import { BlInput } from '@trendyol/baklava/dist/baklava-react';

import options from './mask';
import { elementPredicate } from '../../helpers';

export default function InputWithPrefixByPatternMaskExpression() {
  const maskedInputRef = useMaskito({
    options,
    elementPredicate,
  });

  return (
    <BlInput
      ref={maskedInputRef}
      size="large"
      name="price"
      label="Price"
      placeholder="Enter price"
      icon="money"
    />
  );
}

// examples/input-mask-vue/src/examples/maskito/components/InputWithPrefixByPatternMaskExpression/InputWithPrefixByPatternMaskExpression.vue
<template>
  <bl-input
    v-maskito="options"
    size="large"
    name="price"
    label="Price"
    placeholder="Enter price"
    icon="money"
  />
</template>

<script>
import { defineComponent } from 'vue';
import { maskito } from '@maskito/vue';
import maskOptions from './mask';
import { elementPredicate } from '../../helpers';

export default defineComponent({
  name: 'InputWithPrefixByPatternMaskExpression',
  directives: {
    maskito,
  },
  setup() {
    const options = {
      ...maskOptions,
      elementPredicate,
    };

    return {
      options,
    };
  },
});
</script>
