// examples/input-mask-vue/src/examples/imask/components/InputWithPlaceholderPhone/InputWithPlaceholderPhone.vue
<template>
  <bl-input ref="blInputRef" size="large" icon="phone" label="Phone Number" />
</template>

<script>
import { defineComponent } from 'vue';
import { useIMaskWithObserver } from '../../hooks/useIMaskWithObserver';

export default defineComponent({
  name: 'InputWithPlaceholderPhone',
  setup() {
    const { el: blInputRef } = useIMaskWithObserver({
      mask: '+{1} (num) 000-0000',
      blocks: {
        num: {
          mask: '000',
          placeholderChar: ' ',
        },
      },
      lazy: false,
    });

    return {
      blInputRef,
    };
  },
});
</script>

// examples/input-mask-react/src/examples/imask/components/InputWithPlaceholderPhone/InputWithPlaceholderPhone.jsx
import { BlInput } from '@trendyol/baklava/dist/baklava-react';
import { useIMaskWithObserver } from '../../hooks';

export default function InputWithPlaceholderPhone() {
  const ref = useIMaskWithObserver({
    mask: '+{1} (num) 000-0000',
    blocks: {
      num: {
        mask: '000',
        placeholderChar: ' ',
      },
    },
    lazy: false,
  });

  return <BlInput ref={ref} size="large" icon="phone" label="Phone Number" />;
}
