// examples/input-mask-vue/src/examples/imask/components/InputPhoneUSA/InputPhoneUSA.vue
<template>
  <bl-input
    ref="blInputRef"
    size="large"
    icon="phone"
    label="Phone Number"
    placeholder="Enter phone number"
    name="phone-usa"
    autofocus
  />
</template>

<script>
import { defineComponent } from 'vue';
import { useIMaskWithObserver } from '../../hooks/useIMaskWithObserver';

export default defineComponent({
  name: 'InputPhoneUSA',
  setup() {
    const { el: blInputRef } = useIMaskWithObserver({
      mask: '+1 (000) 000-0000',
    });

    return {
      blInputRef,
    };
  },
});
</script>

// examples/input-mask-react/src/examples/imask/components/InputPhoneUSA/InputPhoneUSA.jsx
import { BlInput } from '@trendyol/baklava/dist/baklava-react';
import { useIMaskWithObserver } from '../../hooks';

export default function InputPhoneUSA() {
  const ref = useIMaskWithObserver({
    mask: '+1 (000) 000-0000',
  });

  return (
    <BlInput
      ref={ref}
      size="large"
      icon="phone"
      label="Phone Number"
      placeholder="Enter phone number"
      name="phone-usa"
      autofocus
    />
  );
}
