// examples/input-mask-react/src/examples/imask/components/InputAmountPostfix/InputAmountPostfix.jsx
import { BlInput } from '@trendyol/baklava/dist/baklava-react';
import { useIMaskWithObserver } from '../../hooks';

const InputAmountPostfix = () => {
  const ref = useIMaskWithObserver({
    mask: 'num%',
    lazy: false,
    blocks: {
      num: {
        mask: Number,
      },
    },
  });

  return (
    <BlInput
      ref={ref}
      size="large"
      name="amount"
      label="Amount"
      placeholder="Enter amount"
      helpText="example: 99%"
      labelFixed
    />
  );
};

export default InputAmountPostfix;

// examples/input-mask-vue/src/examples/imask/components/InputAmountPostfix/InputAmountPostfix.vue
<template>
  <bl-input
    ref="blInputRef"
    size="large"
    name="amount"
    label="Amount"
    placeholder="Enter amount"
    help-text="example: 99%"
    label-fixed
  />
</template>

<script>
import { defineComponent } from 'vue';
import { useIMaskWithObserver } from '../../hooks/useIMaskWithObserver';

export default defineComponent({
  name: 'InputAmountPostfix',
  setup() {
    const { el: blInputRef } = useIMaskWithObserver({
      mask: 'num%',
      lazy: false,
      blocks: {
        num: {
          mask: Number,
        },
      },
    });

    return {
      blInputRef,
    };
  },
});
</script>
