// examples/input-mask-vue/src/examples/maskito/components/InputWithPostfixByPatternMaskExpression/InputWithPostfixByPatternMaskExpression.vue
<template>
  <bl-input
    v-maskito="options"
    size="large"
    name="amount"
    label="Amount"
    placeholder="Enter amount"
    help-text="example: 99%"
    label-fixed
  />
</template>

<script>
import { defineComponent } from 'vue';
import { maskito } from '@maskito/vue';
import maskOptions from './mask';
import { elementPredicate } from '../../helpers';

export default defineComponent({
  name: 'InputWithPostfixByPatternMaskExpression',
  directives: {
    maskito,
  },
  setup() {
    const options = {
      ...maskOptions,
      elementPredicate,
    };

    return {
      options,
    };
  },
});
</script>

// examples/input-mask-react/src/examples/maskito/components/InputWithPostfixByPatternMaskExpression/InputWithPostfixByPatternMaskExpression.jsx
import { useMaskito } from '@maskito/react';
import { BlInput } from '@trendyol/baklava/dist/baklava-react';

import options from './mask';
import { elementPredicate } from '../../helpers';

export default function InputWithPostfixByPatternMaskExpression() {
  const maskedInputRef = useMaskito({
    options,
    elementPredicate,
  });

  return (
    <BlInput
      ref={maskedInputRef}
      size="large"
      name="amount"
      label="Amount"
      placeholder="Enter amount"
      helpText="example: 99%"
      labelFixed
    />
  );
}
